import java.lang.*;
import java.io.*;
class A
{
public static void main(String args[])throws IOException
{
BufferedReader br=new BufferedReader(new InputStreamReader(System.in));
System.out.println("enter the value of a");
int a=Integer.parseInt(br.readLine());
System.out.println("enter the value of b");
int b=Integer.parseInt(br.readLine());
try
{
int c=a/b;
System.out.println("the division is "+c);
}
catch(ArithmeticException ref)
{
System.out.println(ref);
System.out.println("the above statement is the reference statements which is written in the exception stack created by JVM");
}
finally
{
System.out.println("closing the files");
}
}
}
