import java.lang.*;
import java.io.*;
class A extends Exception
{
int a;
int b;
A(int a,int b)
{
this.a=a;
this.b=b;
}
void division()
{
try
{
int c=a/b;
System.out.println("the division is "+c);
}
catch(ArithmeticException e)
{
System.out.println(e);
}
}
void array()
{
try
{
int arr[]={12,23,34,45};
arr[34]=56;
System.out.println("rest of the lines");
}
catch(ArrayIndexOutOfBoundsException e)
{
System.out.println(e);
}
}
}
class Main
{
public static void main(String args[])throws IOException
{
BufferedReader br=new BufferedReader(new InputStreamReader(System.in));
int a=Integer.parseInt(br.readLine());
int b=Integer.parseInt(br.readLine());
A er=new A(a,b);
er.division();
er.array();
System.out.println("rest of the code...........");
}
}
